trigger: none
pool: Default

stages:
- stage: initPlanStage
  jobs:
  - job: InitPlanJOB
    steps:
     - task: TerraformInstaller@1
       inputs:
         terraformVersion: 'latest'
     - task: TerraformTaskV4@4
       inputs:
         provider: 'azurerm'
         command: 'init'
         workingDirectory: '$(System.DefaultWorkingDirectory)/enviroment/Dev'
         backendServiceArm: 'Rameshwarsc'
         backendAzureRmResourceGroupName: 'pipeline-rg'
         backendAzureRmStorageAccountName: 'pipeline097577'
         backendAzureRmContainerName: 'pipelinecon'
         backendAzureRmKey: 'pipeline.terraform.tfstate'
     - task: TerraformTaskV4@4
       inputs:
         provider: 'azurerm'
         command: 'plan'
         workingDirectory: '$(System.DefaultWorkingDirectory)/enviroment/Dev'
         environmentServiceNameAzureRM: 'Rameshwarsc'
     
- stage: manualValidationStage
  pool: server
  jobs:
  - job: ManualValidationJOB
    steps:
     - task: ManualValidation@1
       inputs:
         instructions: 'hi approve'

- stage: INITandxApplyStage
  jobs:
  - job: initApplyJOB
    steps:
     - task: TerraformTaskV4@4
       inputs:
         provider: 'azurerm'
         command: 'init'
         workingDirectory: '$(System.DefaultWorkingDirectory)/enviroment/Dev'
         backendServiceArm: 'Rameshwarsc'
         backendAzureRmResourceGroupName: 'pipeline-rg'
         backendAzureRmStorageAccountName: 'pipeline097577'
         backendAzureRmContainerName: 'pipelinecon'
         backendAzureRmKey: 'pipeline.terraform.tfstate'
     - task: TerraformTaskV4@4
       inputs:
         provider: 'azurerm'
         command: 'apply'
         workingDirectory: '$(System.DefaultWorkingDirectory)/enviroment/Dev'
         commandOptions: '-auto-approve'
         environmentServiceNameAzureRM: 'Rameshwarsc'