trigger: none
pool: default

jobs:
- job: dockerbuild
  steps:
   - task: Docker@2
     inputs:
       containerRegistry: 'abhinewdocker'
       command: 'login'

   - task: Docker@2
     inputs:
       containerRegistry: 'abhinewdocker'
       repository: 'myapp-image'
       command: 'buildAndPush'
       Dockerfile: 'Calculator-App/Dockerfile'
   - task: Kubernetes@1
     inputs:
       connectionType: 'Kubernetes Service Connection'
       kubernetesServiceEndpoint: 'abhinewakssc'
       command: 'apply'
       useConfigurationFile: true
       configuration: 'Kubernetes/Deployment/deployment.yaml'