apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-calculator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-calculator
  template:
    metadata:
      labels:
        app: http-calculator
    spec:
      containers:
        - name: calculator
          image: mymeeacr01.azurecr.io/http-calculator:v1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: http-calculator-service
spec:
  type: LoadBalancer
  selector:
    app: http-calculator
  ports:
    - port: 80
      targetPort: 80
